
# Generated by gitai 0.1.2

BaseModel = require '../BaseModel'

class Blobs extends BaseModel
  init:=>
    @debug "init()"

    @program.command "get"
      .description "获取 blob"
      .arguments "<user> <project> <blob>"
      .action @get



  ###

   method            : get
   summary         : get
   description    : 获取 blob
   header         : userAgent,accept
   path            : user,project,blob
   body            : currentApp,ref,path

  ###

  get: (user,project,blob) =>
    @debug "Blobs::get()"

    @prompt.get [{"name":"userAgent","description":"Enter userAgent","type":"string","required":false},{"name":"accept","description":"Enter accept","type":"string","required":false},{"name":"currentApp","description":"Enter currentApp","type":"string","required":false},{"name":"ref","description":"Enter ref","type":"string","required":false},{"name":"path","description":"Enter path","type":"string","required":false}],(err,params)=>
      if err
        return err
      params = @parseParames params,["userAgent","accept"],[],["currentApp","ref","path"],[]
      @coding.blob.get user,project,blob,params,(data) =>
        @showData data


module.exports = (cmd) -> new Blobs cmd