
# Generated by gitai 0.1.2

BaseModel = require '../BaseModel'

class Files extends BaseModel
  init:=>
    @debug "init()"

    @program.command "checkExisted"
      .description "检查目录下是否有同名的文件"
      .arguments "<user> <project> <dir>"
      .action @checkExisted

    @program.command "uploadNewVersion"
      .description "上传文件新版本"
      .arguments "<user> <project>"
      .action @uploadNewVersion

    @program.command "view"
      .description "删除文件"
      .arguments "<user> <project>"
      .action @view

    @program.command "history"
      .description "删除文件历史"
      .arguments "<user> <project> <id>"
      .action @history

    @program.command "download"
      .description "下载历史文件版本"
      .arguments "<user> <project> <id>"
      .action @download

    @program.command "upload"
      .description "上传私有项目的图片"
      .arguments "<user> <project>"
      .action @upload

    @program.command "download"
      .description "文件下载"
      .arguments "<user> <project> <fileId>"
      .action @download

    @program.command "download"
      .description "文件下载URL"
      .arguments "<user> <project> <fileId>"
      .action @download

    @program.command "edit"
      .description "编辑文件"
      .arguments "<user> <project> <fileId>"
      .action @edit

    @program.command "view"
      .description "查看文件"
      .arguments "<user> <project> <fileId>"
      .action @view

    @program.command "preview"
      .description "图片预览"
      .arguments "<user> <project> <fileId>"
      .action @preview

    @program.command "updateFileRemark"
      .description "修改历史版本备注"
      .arguments "<user> <project> <file_id> <history_id>"
      .action @updateFileRemark

    @program.command "create"
      .description "创建文件"
      .arguments "<user> <project> <folderId>"
      .action @create

    @program.command "history"
      .description "文件历史"
      .arguments "<user> <project> <id>"
      .action @history

    @program.command "mkdir"
      .description "创建文件夹"
      .arguments "<user> <project>"
      .action @mkdir

    @program.command "mkdir"
      .description "删除文件夹"
      .arguments "<user> <project>"
      .action @mkdir

    @program.command "move"
      .description "移动文件"
      .arguments "<user> <project> <dirId>"
      .action @move

    @program.command "renameFolder"
      .description "重命名文件夹"
      .arguments "<user> <project> <dir>"
      .action @renameFolder

    @program.command "files"
      .description "列出某目录下的文件"
      .arguments "<user> <project> <dir>"
      .action @files

    @program.command "folders"
      .description "列出所有一级目录"
      .arguments "<user> <project>"
      .action @folders

    @program.command "folders"
      .description "列出所有目录"
      .arguments "<user> <project>"
      .action @folders

    @program.command "count"
      .description "获取文件夹的文件数"
      .arguments "<user> <project>"
      .action @count



  ###

   method            : get
   summary         : checkExisted
   description    : 检查目录下是否有同名的文件
   path            : user,project,dir
   body            : names

  ###

  checkExisted: (user,project,dir) =>
    @debug "Files::checkExisted()"

    @prompt.get [{"name":"names","description":"Enter names","type":"array","required":false}],(err,params)=>
      if err
        return err
      @coding.file.checkExisted user,project,dir,params, (data) =>
        @showData data

  ###

   method            : post
   summary         : uploadNewVersion
   description    : 上传文件新版本
   path            : user,project

  ###

  uploadNewVersion: (user,project) =>
    @debug "Files::uploadNewVersion()"

    @coding.file.uploadNewVersion user,project,(data) =>
      @showData data

  ###

   method            : delete
   summary         : view
   description    : 删除文件
   path            : user,project
   body            : fileIds

  ###

  view: (user,project) =>
    @debug "Files::view()"

    @prompt.get [{"name":"fileIds","description":"Enter fileIds","type":"array","required":false}],(err,params)=>
      if err
        return err
      @coding.file.view user,project,params, (data) =>
        @showData data

  ###

   method            : delete
   summary         : history
   description    : 删除文件历史
   path            : user,project,id

  ###

  history: (user,project,id) =>
    @debug "Files::history()"

    @coding.file.history user,project,id,(data) =>
      @showData data

  ###

   method            : get
   summary         : download
   description    : 下载历史文件版本
   path            : user,project,id

  ###

  download: (user,project,id) =>
    @debug "Files::download()"

    @coding.file.download user,project,id,(data) =>
      @showData data

  ###

   method            : post
   summary         : upload
   description    : 上传私有项目的图片
   path            : user,project

  ###

  upload: (user,project) =>
    @debug "Files::upload()"

    @coding.file.upload user,project,(data) =>
      @showData data

  ###

   method            : get
   summary         : download
   description    : 文件下载
   path            : user,project,fileId

  ###

  download: (user,project,fileId) =>
    @debug "Files::download()"

    @coding.file.download user,project,fileId,(data) =>
      @showData data

  ###

   method            : get
   summary         : download
   description    : 文件下载URL
   path            : user,project,fileId

  ###

  download: (user,project,fileId) =>
    @debug "Files::download()"

    @coding.file.download user,project,fileId,(data) =>
      @showData data

  ###

   method            : post
   summary         : edit
   description    : 编辑文件
   path            : user,project,fileId
   query            : name,content,fileId

  ###

  edit: (user,project,fileId) =>
    @debug "Files::edit()"

    @prompt.get [{"name":"name","description":"Enter name","type":"string","required":false},{"name":"content","description":"Enter content","type":"string","required":false},{"name":"fileId","description":"Enter fileId","type":"integer","required":false}],(err,params)=>
      if err
        return err
      @coding.file.edit user,project,fileId,params, (data) =>
        @showData data

  ###

   method            : get
   summary         : view
   description    : 查看文件
   path            : user,project,fileId
   query            : type,width,height,flag

  ###

  view: (user,project,fileId) =>
    @debug "Files::view()"

    @prompt.get [{"name":"type","description":"Enter type","type":"integer","required":false},{"name":"width","description":"Enter width","type":"integer","required":false},{"name":"height","description":"Enter height","type":"integer","required":false},{"name":"flag","description":"Enter flag","type":"integer","required":false}],(err,params)=>
      if err
        return err
      @coding.file.view user,project,fileId,params, (data) =>
        @showData data

  ###

   method            : get
   summary         : preview
   description    : 图片预览
   path            : user,project,fileId
   query            : type,width,height

  ###

  preview: (user,project,fileId) =>
    @debug "Files::preview()"

    @prompt.get [{"name":"type","description":"Enter type","type":"integer","required":false},{"name":"width","description":"Enter width","type":"integer","required":false},{"name":"height","description":"Enter height","type":"integer","required":false}],(err,params)=>
      if err
        return err
      @coding.file.preview user,project,fileId,params, (data) =>
        @showData data

  ###

   method            : post
   summary         : updateFileRemark
   description    : 修改历史版本备注
   path            : user,project,file_id,history_id
   query            : remark

  ###

  updateFileRemark: (user,project,file_id,history_id) =>
    @debug "Files::updateFileRemark()"

    @prompt.get [{"name":"remark","description":"Enter remark","type":"string","required":true}],(err,params)=>
      if err
        return err
      @coding.file.updateFileRemark user,project,file_id,history_id,params, (data) =>
        @showData data

  ###

   method            : post
   summary         : create
   description    : 创建文件
   path            : user,project,folderId
   query            : projectFile.deleted_at,projectFile.projects_id,projectFile.files_id,projectFile.comments,projectFile.id,folder.owner_id,folder.parent_id,folder.created_at,folder.updated_at,folder.type,folder.size,folder.name,folder.storage_type,folder.storage_key,folder.history_id,folder.id,name,content,folderId

  ###

  create: (user,project,folderId) =>
    @debug "Files::create()"

    @prompt.get [{"name":"projectFile.deleted_at","description":"Enter projectFile.deleted_at","type":"string","required":false},{"name":"projectFile.projects_id","description":"Enter projectFile.projects_id","type":"integer","required":false},{"name":"projectFile.files_id","description":"Enter projectFile.files_id","type":"integer","required":false},{"name":"projectFile.comments","description":"Enter projectFile.comments","type":"integer","required":false},{"name":"projectFile.id","description":"Enter projectFile.id","type":"integer","required":false},{"name":"folder.owner_id","description":"Enter folder.owner_id","type":"integer","required":false},{"name":"folder.parent_id","description":"Enter folder.parent_id","type":"integer","required":false},{"name":"folder.created_at","description":"Enter folder.created_at","type":"ref","required":false},{"name":"folder.updated_at","description":"Enter folder.updated_at","type":"ref","required":false},{"name":"folder.type","description":"Enter folder.type","type":"integer","required":false},{"name":"folder.size","description":"Enter folder.size","type":"integer","required":false},{"name":"folder.name","description":"Enter folder.name","type":"string","required":false},{"name":"folder.storage_type","description":"Enter folder.storage_type","type":"string","required":false},{"name":"folder.storage_key","description":"Enter folder.storage_key","type":"string","required":false},{"name":"folder.history_id","description":"Enter folder.history_id","type":"integer","required":false},{"name":"folder.id","description":"Enter folder.id","type":"integer","required":false},{"name":"name","description":"Enter name","type":"string","required":false},{"name":"content","description":"Enter content","type":"string","required":false},{"name":"folderId","description":"Enter folderId","type":"integer","required":false}],(err,params)=>
      if err
        return err
      @coding.file.create user,project,folderId,params, (data) =>
        @showData data

  ###

   method            : get
   summary         : history
   description    : 文件历史
   path            : user,project,id
   query            : type,width,height

  ###

  history: (user,project,id) =>
    @debug "Files::history()"

    @prompt.get [{"name":"type","description":"Enter type","type":"integer","required":false},{"name":"width","description":"Enter width","type":"integer","required":false},{"name":"height","description":"Enter height","type":"integer","required":false}],(err,params)=>
      if err
        return err
      @coding.file.history user,project,id,params, (data) =>
        @showData data

  ###

   method            : post
   summary         : mkdir
   description    : 创建文件夹
   path            : user,project
   query            : name,parentId

  ###

  mkdir: (user,project) =>
    @debug "Files::mkdir()"

    @prompt.get [{"name":"name","description":"Enter name","type":"string","required":false},{"name":"parentId","description":"Enter parentId","type":"string","required":false}],(err,params)=>
      if err
        return err
      @coding.file.mkdir user,project,params, (data) =>
        @showData data

  ###

   method            : delete
   summary         : mkdir
   description    : 删除文件夹
   path            : user,project

  ###

  mkdir: (user,project) =>
    @debug "Files::mkdir()"

    @coding.file.mkdir user,project,(data) =>
      @showData data

  ###

   method            : put
   summary         : move
   description    : 移动文件
   path            : user,project,dirId
   query            : fileId

  ###

  move: (user,project,dirId) =>
    @debug "Files::move()"

    @prompt.get [{"name":"fileId","description":"Enter fileId","type":"ref","required":false}],(err,params)=>
      if err
        return err
      @coding.file.move user,project,dirId,params, (data) =>
        @showData data

  ###

   method            : put
   summary         : renameFolder
   description    : 重命名文件夹
   path            : user,project,dir
   query            : name

  ###

  renameFolder: (user,project,dir) =>
    @debug "Files::renameFolder()"

    @prompt.get [{"name":"name","description":"Enter name","type":"string","required":false}],(err,params)=>
      if err
        return err
      @coding.file.renameFolder user,project,dir,params, (data) =>
        @showData data

  ###

   method            : get
   summary         : files
   description    : 列出某目录下的文件
   path            : user,project,dir
   query            : type,width,height,page,pageSize

  ###

  files: (user,project,dir) =>
    @debug "Files::files()"

    @prompt.get [{"name":"type","description":"Enter type","type":"integer","required":false},{"name":"width","description":"Enter width","type":"integer","required":false},{"name":"height","description":"Enter height","type":"integer","required":false},{"name":"page","description":"Enter page","type":"integer","required":false},{"name":"pageSize","description":"Enter pageSize","type":"integer","required":false}],(err,params)=>
      if err
        return err
      @coding.file.files user,project,dir,params, (data) =>
        @showData data

  ###

   method            : get
   summary         : folders
   description    : 列出所有一级目录
   path            : user,project
   query            : page,pageSize

  ###

  folders: (user,project) =>
    @debug "Files::folders()"

    @prompt.get [{"name":"page","description":"Enter page","type":"integer","required":false},{"name":"pageSize","description":"Enter pageSize","type":"integer","required":false}],(err,params)=>
      if err
        return err
      @coding.file.folders user,project,params, (data) =>
        @showData data

  ###

   method            : get
   summary         : folders
   description    : 列出所有目录
   path            : user,project
   query            : page,pageSize

  ###

  folders: (user,project) =>
    @debug "Files::folders()"

    @prompt.get [{"name":"page","description":"Enter page","type":"integer","required":false},{"name":"pageSize","description":"Enter pageSize","type":"integer","required":false}],(err,params)=>
      if err
        return err
      @coding.file.folders user,project,params, (data) =>
        @showData data

  ###

   method            : get
   summary         : count
   description    : 获取文件夹的文件数
   path            : user,project

  ###

  count: (user,project) =>
    @debug "Files::count()"

    @coding.file.count user,project,(data) =>
      @showData data


module.exports = (cmd) -> new Files cmd