
# Generated by gitai 0.1.2

BaseModel = require '../BaseModel'

class MergeRequests extends BaseModel
  init:=>
    @debug "init()"

    @program.command "create"
      .description "创建 MergeRequest"
      .arguments "<user> <project>"
      .action @create

    @program.command "get"
      .description "显示某个 MergeRequest"
      .arguments "<user> <project> <iid>"
      .action @get

    @program.command "update"
      .description "更新某个 MergeRequest"
      .arguments "<user> <project> <iid>"
      .action @update

    @program.command "cancel"
      .description "取消 MergeRequest"
      .arguments "<user> <project> <iid>"
      .action @cancel

    @program.command "merge"
      .description "合并某个 MergeRequest"
      .arguments "<user> <project> <iid>"
      .action @merge

    @program.command "refuse"
      .description "拒绝某个 MergeRequest"
      .arguments "<user> <project> <iid>"
      .action @refuse

    @program.command "list"
      .description "MergeRequest 列表"
      .arguments "<user> <project> <status>"
      .action @list



  ###

   method            : post
   summary         : create
   description    : 创建 MergeRequest
   path            : user,project
   query            : srcBranch,desBranch,title,content,reviewers,tasks

  ###

  create: (user,project) =>
    @debug "MergeRequests::create()"

    @prompt.get [{"name":"srcBranch","description":"Enter srcBranch","type":"string","required":false},{"name":"desBranch","description":"Enter desBranch","type":"string","required":false},{"name":"title","description":"Enter title","type":"string","required":false},{"name":"content","description":"Enter content","type":"string","required":false},{"name":"reviewers","description":"Enter reviewers","type":"string","required":false},{"name":"tasks","description":"Enter tasks","type":"string","required":false}],(err,params)=>
      if err
        return err
      params = @parseParames params,[],["srcBranch","desBranch","title","content","reviewers","tasks"],[],[]
      @coding.mergeRequest.create user,project,params,(data) =>
        @showData data

  ###

   method            : get
   summary         : get
   description    : 显示某个 MergeRequest
   path            : user,project,iid
   query            : diff

  ###

  get: (user,project,iid) =>
    @debug "MergeRequests::get()"

    @prompt.get [{"name":"diff","description":"Enter diff","type":"string","required":false}],(err,params)=>
      if err
        return err
      params = @parseParames params,[],["diff"],[],[]
      @coding.mergeRequest.get user,project,iid,params,(data) =>
        @showData data

  ###

   method            : put
   summary         : update
   description    : 更新某个 MergeRequest
   path            : user,project,iid
   query            : srcBranch,desBranch,title,content,reviewers,tasks

  ###

  update: (user,project,iid) =>
    @debug "MergeRequests::update()"

    @prompt.get [{"name":"srcBranch","description":"Enter srcBranch","type":"string","required":false},{"name":"desBranch","description":"Enter desBranch","type":"string","required":false},{"name":"title","description":"Enter title","type":"string","required":false},{"name":"content","description":"Enter content","type":"string","required":false},{"name":"reviewers","description":"Enter reviewers","type":"string","required":false},{"name":"tasks","description":"Enter tasks","type":"string","required":false}],(err,params)=>
      if err
        return err
      params = @parseParames params,[],["srcBranch","desBranch","title","content","reviewers","tasks"],[],[]
      @coding.mergeRequest.update user,project,iid,params,(data) =>
        @showData data

  ###

   method            : post
   summary         : cancel
   description    : 取消 MergeRequest
   path            : user,project,iid

  ###

  cancel: (user,project,iid) =>
    @debug "MergeRequests::cancel()"

    @coding.mergeRequest.cancel user,project,iid,(data) =>
      @showData data

  ###

   method            : post
   summary         : merge
   description    : 合并某个 MergeRequest
   path            : user,project,iid
   query            : message,del_source_branch

  ###

  merge: (user,project,iid) =>
    @debug "MergeRequests::merge()"

    @prompt.get [{"name":"message","description":"Enter message","type":"string","required":false},{"name":"del_source_branch","description":"Enter del_source_branch","type":"boolean","required":false}],(err,params)=>
      if err
        return err
      params = @parseParames params,[],["message","del_source_branch"],[],[]
      @coding.mergeRequest.merge user,project,iid,params,(data) =>
        @showData data

  ###

   method            : post
   summary         : refuse
   description    : 拒绝某个 MergeRequest
   path            : user,project,iid

  ###

  refuse: (user,project,iid) =>
    @debug "MergeRequests::refuse()"

    @coding.mergeRequest.refuse user,project,iid,(data) =>
      @showData data

  ###

   method            : get
   summary         : list
   description    : MergeRequest 列表
   path            : user,project,status
   query            : page,pageSize

  ###

  list: (user,project,status) =>
    @debug "MergeRequests::list()"

    @prompt.get [{"name":"page","description":"Enter page","type":"integer","required":false},{"name":"pageSize","description":"Enter pageSize","type":"integer","required":false}],(err,params)=>
      if err
        return err
      params = @parseParames params,[],["page","pageSize"],[],[]
      @coding.mergeRequest.list user,project,status,params,(data) =>
        @showData data


module.exports = (cmd) -> new MergeRequests cmd