
# Generated by gitai 0.1.2

BaseModel = require '../BaseModel'

class Projects extends BaseModel
  init:=>
    @debug "init()"

    @program.command "pinProject"
      .description "获取常用项目列表"
      .action @pinProject

    @program.command "pinProject"
      .description "设置常用项目"
      .action @pinProject

    @program.command "pinProject"
      .description "取消常用项目"
      .action @pinProject

    @program.command "update"
      .description "更新项目信息"
      .action @update

    @program.command "recommendedList"
      .description "推荐项目list"
      .action @recommendedList

    @program.command "publicProjects"
      .description "公有项目列表"
      .action @publicProjects

    @program.command "queryByName"
      .description "通过名称查询"
      .arguments "<user> <project>"
      .action @queryByName

    @program.command "deleteProject"
      .description "删除项目"
      .arguments "<user> <project>"
      .action @deleteProject

    @program.command "setProjectIcon"
      .description "设置项目图标"
      .arguments "<user> <project>"
      .action @setProjectIcon

    @program.command "star"
      .description "收藏项目"
      .arguments "<user> <project>"
      .action @star

    @program.command "stared"
      .description "项目是否被收藏"
      .arguments "<user> <project>"
      .action @stared

    @program.command "unstar"
      .description "项目取消收藏"
      .arguments "<user> <project>"
      .action @unstar

    @program.command "unwatch"
      .description "项目取消关注"
      .arguments "<user> <project>"
      .action @unwatch

    @program.command "visitProject"
      .description "更新项目阅读时间"
      .arguments "<user> <project>"
      .action @visitProject

    @program.command "watch"
      .description "关注项目"
      .arguments "<user> <project>"
      .action @watch

    @program.command "watched"
      .description "项目是否被关注"
      .arguments "<user> <project>"
      .action @watched

    @program.command "watched"
      .description "项目关注者"
      .arguments "<user> <project>"
      .action @watched

    @program.command "projectList"
      .description "我的项目列表"
      .action @projectList

    @program.command "privateProjects"
      .description "私有项目列表"
      .action @privateProjects

    @program.command "privateProjects"
      .description "私有项目列表"
      .action @privateProjects

    @program.command "privateProjects"
      .description "私有项目列表"
      .action @privateProjects

    @program.command "privateProjects"
      .description "私有项目列表"
      .action @privateProjects

    @program.command "privateProjects"
      .description "私有项目列表"
      .action @privateProjects

    @program.command "privateProjects"
      .description "私有项目列表"
      .action @privateProjects

    @program.command "createProject"
      .description "创建项目"
      .arguments "<user>"
      .action @createProject

    @program.command "publicProjects"
      .description "公有项目列表"
      .arguments "<user>"
      .action @publicProjects

    @program.command "publicProjects"
      .description "公有项目列表"
      .arguments "<user>"
      .action @publicProjects

    @program.command "publicProjects"
      .description "公有项目列表"
      .arguments "<user>"
      .action @publicProjects

    @program.command "publicProjects"
      .description "公有项目列表"
      .arguments "<user>"
      .action @publicProjects

    @program.command "publicProjects"
      .description "公有项目列表"
      .arguments "<user>"
      .action @publicProjects

    @program.command "publicProjects"
      .description "公有项目列表"
      .arguments "<user>"
      .action @publicProjects



  ###

   method            : get
   summary         : pinProject
   description    : 获取常用项目列表
   query            : page,pageSize

  ###

  pinProject: () =>
    @debug "Projects::pinProject()"

    @prompt.get [{"name":"page","description":"Enter page","type":"integer","required":false},{"name":"pageSize","description":"Enter pageSize","type":"integer","required":false}],(err,params)=>
      if err
        return err
      params = @parseParames params,[],["page","pageSize"],[],[]
      @coding.project.pinProject params,(data) =>
        @showData data

  ###

   method            : post
   summary         : pinProject
   description    : 设置常用项目
   body            : ids

  ###

  pinProject: () =>
    @debug "Projects::pinProject()"

    @prompt.get [{"name":"ids","description":"Enter ids","type":"string","required":false}],(err,params)=>
      if err
        return err
      params = @parseParames params,[],[],["ids"],[]
      @coding.project.pinProject params,(data) =>
        @showData data

  ###

   method            : delete
   summary         : pinProject
   description    : 取消常用项目
   body            : ids

  ###

  pinProject: () =>
    @debug "Projects::pinProject()"

    @prompt.get [{"name":"ids","description":"Enter ids","type":"string","required":false}],(err,params)=>
      if err
        return err
      params = @parseParames params,[],[],["ids"],[]
      @coding.project.pinProject params,(data) =>
        @showData data

  ###

   method            : put
   summary         : update
   description    : 更新项目信息
   query            : id,name,description

  ###

  update: () =>
    @debug "Projects::update()"

    @prompt.get [{"name":"id","description":"Enter id","type":"string","required":false},{"name":"name","description":"Enter name","type":"string","required":false},{"name":"description","description":"Enter description","type":"string","required":false}],(err,params)=>
      if err
        return err
      params = @parseParames params,[],["id","name","description"],[],[]
      @coding.project.update params,(data) =>
        @showData data

  ###

   method            : get
   summary         : recommendedList
   description    : 推荐项目list

  ###

  recommendedList: () =>
    @debug "Projects::recommendedList()"

    @coding.project.recommendedList (data) =>
      @showData data

  ###

   method            : get
   summary         : publicProjects
   description    : 公有项目列表
   query            : page,pageSize

  ###

  publicProjects: () =>
    @debug "Projects::publicProjects()"

    @prompt.get [{"name":"page","description":"Enter page","type":"integer","required":false},{"name":"pageSize","description":"Enter pageSize","type":"integer","required":false}],(err,params)=>
      if err
        return err
      params = @parseParames params,[],["page","pageSize"],[],[]
      @coding.project.publicProjects params,(data) =>
        @showData data

  ###

   method            : get
   summary         : queryByName
   description    : 通过名称查询
   path            : user,project

  ###

  queryByName: (user,project) =>
    @debug "Projects::queryByName()"

    @coding.project.queryByName user,project,(data) =>
      @showData data

  ###

   method            : delete
   summary         : deleteProject
   description    : 删除项目
   path            : user,project
   query            : name

  ###

  deleteProject: (user,project) =>
    @debug "Projects::deleteProject()"

    @prompt.get [{"name":"name","description":"Enter name","type":"string","required":false}],(err,params)=>
      if err
        return err
      params = @parseParames params,[],["name"],[],[]
      @coding.project.deleteProject user,project,params,(data) =>
        @showData data

  ###

   method            : post
   summary         : setProjectIcon
   description    : 设置项目图标
   path            : user,project

  ###

  setProjectIcon: (user,project) =>
    @debug "Projects::setProjectIcon()"

    @coding.project.setProjectIcon user,project,(data) =>
      @showData data

  ###

   method            : post
   summary         : star
   description    : 收藏项目
   path            : user,project

  ###

  star: (user,project) =>
    @debug "Projects::star()"

    @coding.project.star user,project,(data) =>
      @showData data

  ###

   method            : post
   summary         : stared
   description    : 项目是否被收藏
   path            : user,project

  ###

  stared: (user,project) =>
    @debug "Projects::stared()"

    @coding.project.stared user,project,(data) =>
      @showData data

  ###

   method            : post
   summary         : unstar
   description    : 项目取消收藏
   path            : user,project

  ###

  unstar: (user,project) =>
    @debug "Projects::unstar()"

    @coding.project.unstar user,project,(data) =>
      @showData data

  ###

   method            : post
   summary         : unwatch
   description    : 项目取消关注
   path            : user,project

  ###

  unwatch: (user,project) =>
    @debug "Projects::unwatch()"

    @coding.project.unwatch user,project,(data) =>
      @showData data

  ###

   method            : get
   summary         : visitProject
   description    : 更新项目阅读时间
   path            : user,project

  ###

  visitProject: (user,project) =>
    @debug "Projects::visitProject()"

    @coding.project.visitProject user,project,(data) =>
      @showData data

  ###

   method            : post
   summary         : watch
   description    : 关注项目
   path            : user,project

  ###

  watch: (user,project) =>
    @debug "Projects::watch()"

    @coding.project.watch user,project,(data) =>
      @showData data

  ###

   method            : post
   summary         : watched
   description    : 项目是否被关注
   path            : user,project

  ###

  watched: (user,project) =>
    @debug "Projects::watched()"

    @coding.project.watched user,project,(data) =>
      @showData data

  ###

   method            : get
   summary         : watched
   description    : 项目关注者
   path            : user,project

  ###

  watched: (user,project) =>
    @debug "Projects::watched()"

    @coding.project.watched user,project,(data) =>
      @showData data

  ###

   method            : get
   summary         : projectList
   description    : 我的项目列表
   query            : type,sort,page,pageSize

  ###

  projectList: () =>
    @debug "Projects::projectList()"

    @prompt.get [{"name":"type","description":"Enter type","type":"string","required":false},{"name":"sort","description":"Enter sort","type":"string","required":false},{"name":"page","description":"Enter page","type":"integer","required":false},{"name":"pageSize","description":"Enter pageSize","type":"integer","required":false}],(err,params)=>
      if err
        return err
      params = @parseParames params,[],["type","sort","page","pageSize"],[],[]
      @coding.project.projectList params,(data) =>
        @showData data

  ###

   method            : get
   summary         : privateProjects
   description    : 私有项目列表
   query            : type,page,pageSize

  ###

  privateProjects: () =>
    @debug "Projects::privateProjects()"

    @prompt.get [{"name":"type","description":"Enter type","type":"string","required":false},{"name":"page","description":"Enter page","type":"integer","required":false},{"name":"pageSize","description":"Enter pageSize","type":"integer","required":false}],(err,params)=>
      if err
        return err
      params = @parseParames params,[],["type","page","pageSize"],[],[]
      @coding.project.privateProjects params,(data) =>
        @showData data

  ###

   method            : post
   summary         : privateProjects
   description    : 私有项目列表
   query            : type,page,pageSize

  ###

  privateProjects: () =>
    @debug "Projects::privateProjects()"

    @prompt.get [{"name":"type","description":"Enter type","type":"string","required":false},{"name":"page","description":"Enter page","type":"integer","required":false},{"name":"pageSize","description":"Enter pageSize","type":"integer","required":false}],(err,params)=>
      if err
        return err
      params = @parseParames params,[],["type","page","pageSize"],[],[]
      @coding.project.privateProjects params,(data) =>
        @showData data

  ###

   method            : put
   summary         : privateProjects
   description    : 私有项目列表
   query            : type,page,pageSize

  ###

  privateProjects: () =>
    @debug "Projects::privateProjects()"

    @prompt.get [{"name":"type","description":"Enter type","type":"string","required":false},{"name":"page","description":"Enter page","type":"integer","required":false},{"name":"pageSize","description":"Enter pageSize","type":"integer","required":false}],(err,params)=>
      if err
        return err
      params = @parseParames params,[],["type","page","pageSize"],[],[]
      @coding.project.privateProjects params,(data) =>
        @showData data

  ###

   method            : delete
   summary         : privateProjects
   description    : 私有项目列表
   query            : type,page,pageSize

  ###

  privateProjects: () =>
    @debug "Projects::privateProjects()"

    @prompt.get [{"name":"type","description":"Enter type","type":"string","required":false},{"name":"page","description":"Enter page","type":"integer","required":false},{"name":"pageSize","description":"Enter pageSize","type":"integer","required":false}],(err,params)=>
      if err
        return err
      params = @parseParames params,[],["type","page","pageSize"],[],[]
      @coding.project.privateProjects params,(data) =>
        @showData data

  ###

   method            : options
   summary         : privateProjects
   description    : 私有项目列表
   query            : type,page,pageSize

  ###

  privateProjects: () =>
    @debug "Projects::privateProjects()"

    @prompt.get [{"name":"type","description":"Enter type","type":"string","required":false},{"name":"page","description":"Enter page","type":"integer","required":false},{"name":"pageSize","description":"Enter pageSize","type":"integer","required":false}],(err,params)=>
      if err
        return err
      params = @parseParames params,[],["type","page","pageSize"],[],[]
      @coding.project.privateProjects params,(data) =>
        @showData data

  ###

   method            : patch
   summary         : privateProjects
   description    : 私有项目列表
   query            : type,page,pageSize

  ###

  privateProjects: () =>
    @debug "Projects::privateProjects()"

    @prompt.get [{"name":"type","description":"Enter type","type":"string","required":false},{"name":"page","description":"Enter page","type":"integer","required":false},{"name":"pageSize","description":"Enter pageSize","type":"integer","required":false}],(err,params)=>
      if err
        return err
      params = @parseParames params,[],["type","page","pageSize"],[],[]
      @coding.project.privateProjects params,(data) =>
        @showData data

  ###

   method            : post
   summary         : createProject
   description    : 创建项目
   path            : user
   formData        : name,description,type,gitEnabled,gitIgnore,gitReadmeEnabled,gitLicense,importFrom,vcsType,icon

  ###

  createProject: (user) =>
    @debug "Projects::createProject()"

    @prompt.get [{"name":"name","description":"Enter name","type":"string","required":false},{"name":"description","description":"Enter description","type":"string","required":false},{"name":"type","description":"Enter type","type":"string","required":false},{"name":"gitEnabled","description":"Enter gitEnabled","type":"string","required":false},{"name":"gitIgnore","description":"Enter gitIgnore","type":"string","required":false},{"name":"gitReadmeEnabled","description":"Enter gitReadmeEnabled","type":"string","required":false},{"name":"gitLicense","description":"Enter gitLicense","type":"string","required":false},{"name":"importFrom","description":"Enter importFrom","type":"string","required":false},{"name":"vcsType","description":"Enter vcsType","type":"string","required":false},{"name":"icon","description":"Enter icon","type":"file","required":false}],(err,params)=>
      if err
        return err
      params = @parseParames params,[],[],[],["name","description","type","gitEnabled","gitIgnore","gitReadmeEnabled","gitLicense","importFrom","vcsType","icon"]
      @coding.project.createProject user,params,(data) =>
        @showData data

  ###

   method            : get
   summary         : publicProjects
   description    : 公有项目列表
   path            : user
   query            : type,page,pageSize

  ###

  publicProjects: (user) =>
    @debug "Projects::publicProjects()"

    @prompt.get [{"name":"type","description":"Enter type","type":"string","required":false},{"name":"page","description":"Enter page","type":"integer","required":false},{"name":"pageSize","description":"Enter pageSize","type":"integer","required":false}],(err,params)=>
      if err
        return err
      params = @parseParames params,[],["type","page","pageSize"],[],[]
      @coding.project.publicProjects user,params,(data) =>
        @showData data

  ###

   method            : post
   summary         : publicProjects
   description    : 公有项目列表
   path            : user
   query            : type,page,pageSize

  ###

  publicProjects: (user) =>
    @debug "Projects::publicProjects()"

    @prompt.get [{"name":"type","description":"Enter type","type":"string","required":false},{"name":"page","description":"Enter page","type":"integer","required":false},{"name":"pageSize","description":"Enter pageSize","type":"integer","required":false}],(err,params)=>
      if err
        return err
      params = @parseParames params,[],["type","page","pageSize"],[],[]
      @coding.project.publicProjects user,params,(data) =>
        @showData data

  ###

   method            : put
   summary         : publicProjects
   description    : 公有项目列表
   path            : user
   query            : type,page,pageSize

  ###

  publicProjects: (user) =>
    @debug "Projects::publicProjects()"

    @prompt.get [{"name":"type","description":"Enter type","type":"string","required":false},{"name":"page","description":"Enter page","type":"integer","required":false},{"name":"pageSize","description":"Enter pageSize","type":"integer","required":false}],(err,params)=>
      if err
        return err
      params = @parseParames params,[],["type","page","pageSize"],[],[]
      @coding.project.publicProjects user,params,(data) =>
        @showData data

  ###

   method            : delete
   summary         : publicProjects
   description    : 公有项目列表
   path            : user
   query            : type,page,pageSize

  ###

  publicProjects: (user) =>
    @debug "Projects::publicProjects()"

    @prompt.get [{"name":"type","description":"Enter type","type":"string","required":false},{"name":"page","description":"Enter page","type":"integer","required":false},{"name":"pageSize","description":"Enter pageSize","type":"integer","required":false}],(err,params)=>
      if err
        return err
      params = @parseParames params,[],["type","page","pageSize"],[],[]
      @coding.project.publicProjects user,params,(data) =>
        @showData data

  ###

   method            : options
   summary         : publicProjects
   description    : 公有项目列表
   path            : user
   query            : type,page,pageSize

  ###

  publicProjects: (user) =>
    @debug "Projects::publicProjects()"

    @prompt.get [{"name":"type","description":"Enter type","type":"string","required":false},{"name":"page","description":"Enter page","type":"integer","required":false},{"name":"pageSize","description":"Enter pageSize","type":"integer","required":false}],(err,params)=>
      if err
        return err
      params = @parseParames params,[],["type","page","pageSize"],[],[]
      @coding.project.publicProjects user,params,(data) =>
        @showData data

  ###

   method            : patch
   summary         : publicProjects
   description    : 公有项目列表
   path            : user
   query            : type,page,pageSize

  ###

  publicProjects: (user) =>
    @debug "Projects::publicProjects()"

    @prompt.get [{"name":"type","description":"Enter type","type":"string","required":false},{"name":"page","description":"Enter page","type":"integer","required":false},{"name":"pageSize","description":"Enter pageSize","type":"integer","required":false}],(err,params)=>
      if err
        return err
      params = @parseParames params,[],["type","page","pageSize"],[],[]
      @coding.project.publicProjects user,params,(data) =>
        @showData data


module.exports = (cmd) -> new Projects cmd