
# Generated by gitai 0.1.2

BaseModel = require '../BaseModel'

class ProjectTopics extends BaseModel
  init:=>
    @debug "init()"

    @program.command "list"
      .description "项目讨论列表"
      .arguments "<user> <project>"
      .action @list

    @program.command "create"
      .description "创建讨论/发表评论"
      .arguments "<user> <project>"
      .action @create

    @program.command "count"
      .description "所有讨论的个数和我的讨论的个数"
      .arguments "<user> <project>"
      .action @count

    @program.command "getProjectTopicByLabel"
      .description "通过标签获得讨论列表"
      .arguments "<user> <project> <id>"
      .action @getProjectTopicByLabel

    @program.command "count"
      .description "所有讨论的个数和我的讨论的个数"
      .arguments "<user> <project>"
      .action @count

    @program.command "list"
      .description "我的讨论"
      .arguments "<user> <project>"
      .action @list

    @program.command "watchedProjectTopicList"
      .description "获取我关注的讨论列表"
      .arguments "<user> <project>"
      .action @watchedProjectTopicList

    @program.command "detail"
      .description "讨论详情"
      .arguments "<user> <project> <id>"
      .action @detail

    @program.command "update"
      .description "更新讨论"
      .arguments "<user> <project> <id>"
      .action @update

    @program.command "del"
      .description "删除讨论/删除讨论评论"
      .arguments "<user> <project> <id>"
      .action @del

    @program.command "comments"
      .description "讨论评论列表"
      .arguments "<user> <project> <id>"
      .action @comments

    @program.command "addTopicLabel"
      .description "讨论添加标签"
      .arguments "<user> <project> <id> <labelId>"
      .action @addTopicLabel

    @program.command "deleteTopicLabel"
      .description "删除讨论标签"
      .arguments "<user> <project> <id> <labelId>"
      .action @deleteTopicLabel

    @program.command "operateTopicLabel"
      .description "批量操作讨论标签"
      .arguments "<user> <project> <id>"
      .action @operateTopicLabel

    @program.command "watch"
      .description "关注讨论"
      .arguments "<user> <project> <id>"
      .action @watch

    @program.command "watchers"
      .description "获取关注该讨论的用户"
      .arguments "<user> <project> <id>"
      .action @watchers



  ###

   method            : get
   summary         : list
   description    : 项目讨论列表
   path            : user,project
   query            : orderBy,page,pageSize

  ###

  list: (user,project) =>
    @debug "ProjectTopics::list()"

    @prompt.get [{"name":"orderBy","description":"Enter orderBy","type":"integer","required":false},{"name":"page","description":"Enter page","type":"integer","required":false},{"name":"pageSize","description":"Enter pageSize","type":"integer","required":false}],(err,params)=>
      if err
        return err
      @coding.projectTopic.list user,project,params, (data) =>
        @showData data

  ###

   method            : post
   summary         : create
   description    : 创建讨论/发表评论
   path            : user,project
   query            : parent,title,content,label,type

  ###

  create: (user,project) =>
    @debug "ProjectTopics::create()"

    @prompt.get [{"name":"parent","description":"Enter parent","type":"integer","required":false},{"name":"title","description":"Enter title","type":"string","required":false},{"name":"content","description":"Enter content","type":"string","required":false},{"name":"label","description":"Enter label","type":"string","required":false},{"name":"type","description":"Enter type","type":"integer","required":false}],(err,params)=>
      if err
        return err
      @coding.projectTopic.create user,project,params, (data) =>
        @showData data

  ###

   method            : get
   summary         : count
   description    : 所有讨论的个数和我的讨论的个数
   path            : user,project

  ###

  count: (user,project) =>
    @debug "ProjectTopics::count()"

    @coding.projectTopic.count user,project,(data) =>
      @showData data

  ###

   method            : get
   summary         : getProjectTopicByLabel
   description    : 通过标签获得讨论列表
   path            : user,project,id
   query            : orderBy,page,pageSize

  ###

  getProjectTopicByLabel: (user,project,id) =>
    @debug "ProjectTopics::getProjectTopicByLabel()"

    @prompt.get [{"name":"orderBy","description":"Enter orderBy","type":"integer","required":false},{"name":"page","description":"Enter page","type":"integer","required":false},{"name":"pageSize","description":"Enter pageSize","type":"integer","required":false}],(err,params)=>
      if err
        return err
      @coding.projectTopic.getProjectTopicByLabel user,project,id,params, (data) =>
        @showData data

  ###

   method            : get
   summary         : count
   description    : 所有讨论的个数和我的讨论的个数
   path            : user,project

  ###

  count: (user,project) =>
    @debug "ProjectTopics::count()"

    @coding.projectTopic.count user,project,(data) =>
      @showData data

  ###

   method            : get
   summary         : list
   description    : 我的讨论
   path            : user,project
   query            : orderBy,page,pageSize

  ###

  list: (user,project) =>
    @debug "ProjectTopics::list()"

    @prompt.get [{"name":"orderBy","description":"Enter orderBy","type":"integer","required":false},{"name":"page","description":"Enter page","type":"integer","required":false},{"name":"pageSize","description":"Enter pageSize","type":"integer","required":false}],(err,params)=>
      if err
        return err
      @coding.projectTopic.list user,project,params, (data) =>
        @showData data

  ###

   method            : get
   summary         : watchedProjectTopicList
   description    : 获取我关注的讨论列表
   path            : user,project
   query            : orderBy,page,pageSize

  ###

  watchedProjectTopicList: (user,project) =>
    @debug "ProjectTopics::watchedProjectTopicList()"

    @prompt.get [{"name":"orderBy","description":"Enter orderBy","type":"integer","required":false},{"name":"page","description":"Enter page","type":"integer","required":false},{"name":"pageSize","description":"Enter pageSize","type":"integer","required":false}],(err,params)=>
      if err
        return err
      @coding.projectTopic.watchedProjectTopicList user,project,params, (data) =>
        @showData data

  ###

   method            : get
   summary         : detail
   description    : 讨论详情
   path            : user,project,id
   query            : type,toc

  ###

  detail: (user,project,id) =>
    @debug "ProjectTopics::detail()"

    @prompt.get [{"name":"type","description":"Enter type","type":"integer","required":false},{"name":"toc","description":"Enter toc","type":"boolean","required":false}],(err,params)=>
      if err
        return err
      @coding.projectTopic.detail user,project,id,params, (data) =>
        @showData data

  ###

   method            : put
   summary         : update
   description    : 更新讨论
   path            : user,project,id
   query            : topic_id,title,content,label

  ###

  update: (user,project,id) =>
    @debug "ProjectTopics::update()"

    @prompt.get [{"name":"topic_id","description":"Enter topic_id","type":"integer","required":false},{"name":"title","description":"Enter title","type":"string","required":false},{"name":"content","description":"Enter content","type":"string","required":false},{"name":"label","description":"Enter label","type":"string","required":false}],(err,params)=>
      if err
        return err
      @coding.projectTopic.update user,project,id,params, (data) =>
        @showData data

  ###

   method            : delete
   summary         : del
   description    : 删除讨论/删除讨论评论
   path            : user,project,id

  ###

  del: (user,project,id) =>
    @debug "ProjectTopics::del()"

    @coding.projectTopic.del user,project,id,(data) =>
      @showData data

  ###

   method            : get
   summary         : comments
   description    : 讨论评论列表
   path            : user,project,id
   query            : page,pageSize,type

  ###

  comments: (user,project,id) =>
    @debug "ProjectTopics::comments()"

    @prompt.get [{"name":"page","description":"Enter page","type":"integer","required":false},{"name":"pageSize","description":"Enter pageSize","type":"integer","required":false},{"name":"type","description":"Enter type","type":"integer","required":false}],(err,params)=>
      if err
        return err
      @coding.projectTopic.comments user,project,id,params, (data) =>
        @showData data

  ###

   method            : post
   summary         : addTopicLabel
   description    : 讨论添加标签
   path            : user,project,id,labelId

  ###

  addTopicLabel: (user,project,id,labelId) =>
    @debug "ProjectTopics::addTopicLabel()"

    @coding.projectTopic.addTopicLabel user,project,id,labelId,(data) =>
      @showData data

  ###

   method            : delete
   summary         : deleteTopicLabel
   description    : 删除讨论标签
   path            : user,project,id,labelId

  ###

  deleteTopicLabel: (user,project,id,labelId) =>
    @debug "ProjectTopics::deleteTopicLabel()"

    @coding.projectTopic.deleteTopicLabel user,project,id,labelId,(data) =>
      @showData data

  ###

   method            : post
   summary         : operateTopicLabel
   description    : 批量操作讨论标签
   path            : user,project,id
   query            : labelIdStrs

  ###

  operateTopicLabel: (user,project,id) =>
    @debug "ProjectTopics::operateTopicLabel()"

    @prompt.get [{"name":"labelIdStrs","description":"Enter labelIdStrs","type":"string","required":true}],(err,params)=>
      if err
        return err
      @coding.projectTopic.operateTopicLabel user,project,id,params, (data) =>
        @showData data

  ###

   method            : post
   summary         : watch
   description    : 关注讨论
   path            : user,project,id

  ###

  watch: (user,project,id) =>
    @debug "ProjectTopics::watch()"

    @coding.projectTopic.watch user,project,id,(data) =>
      @showData data

  ###

   method            : get
   summary         : watchers
   description    : 获取关注该讨论的用户
   path            : user,project,id
   query            : page,pageSize

  ###

  watchers: (user,project,id) =>
    @debug "ProjectTopics::watchers()"

    @prompt.get [{"name":"page","description":"Enter page","type":"integer","required":false},{"name":"pageSize","description":"Enter pageSize","type":"integer","required":false}],(err,params)=>
      if err
        return err
      @coding.projectTopic.watchers user,project,id,params, (data) =>
        @showData data


module.exports = (cmd) -> new ProjectTopics cmd