
# Generated by gitai 0.1.2

BaseModel = require '../BaseModel'

class PullRequests extends BaseModel
  init:=>
    @debug "init()"

    @program.command "create"
      .description "创建 PullRequest"
      .arguments "<user> <project>"
      .action @create

    @program.command "get"
      .description "获取某个 PullRequest"
      .arguments "<user> <project> <iid>"
      .action @get

    @program.command "cancle"
      .description "取消 PullRequest"
      .arguments "<user> <project> <iid>"
      .action @cancle

    @program.command "comments"
      .description "PullRequest 评论列表"
      .arguments "<user> <project> <iid>"
      .action @comments

    @program.command "commits"
      .description "获取某个 PullRequest 的评论"
      .arguments "<user> <project> <iid>"
      .action @commits

    @program.command "merge"
      .description "合并 PullRequest"
      .arguments "<user> <project> <iid>"
      .action @merge

    @program.command "refuse"
      .description "拒绝 PullRequest"
      .arguments "<user> <project> <iid>"
      .action @refuse

    @program.command "list"
      .description "PullRequest 列表"
      .arguments "<user> <project> <status>"
      .action @list



  ###

   method            : get
   summary         : create
   description    : 创建 PullRequest
   path            : user,project
   query            : src_branch,des_user_name,des_project_name,des_branch,diff

  ###

  create: (user,project) =>
    @debug "PullRequests::create()"

    @prompt.get [{"name":"src_branch","description":"Enter src_branch","type":"string","required":false},{"name":"des_user_name","description":"Enter des_user_name","type":"string","required":false},{"name":"des_project_name","description":"Enter des_project_name","type":"string","required":false},{"name":"des_branch","description":"Enter des_branch","type":"string","required":false},{"name":"diff","description":"Enter diff","type":"string","required":false}],(err,params)=>
      if err
        return err
      params = @parseParames params,[],["src_branch","des_user_name","des_project_name","des_branch","diff"],[],[]
      @coding.pullRequest.create user,project,params,(data) =>
        @showData data

  ###

   method            : get
   summary         : get
   description    : 获取某个 PullRequest
   path            : user,project,iid
   query            : diff

  ###

  get: (user,project,iid) =>
    @debug "PullRequests::get()"

    @prompt.get [{"name":"diff","description":"Enter diff","type":"string","required":false}],(err,params)=>
      if err
        return err
      params = @parseParames params,[],["diff"],[],[]
      @coding.pullRequest.get user,project,iid,params,(data) =>
        @showData data

  ###

   method            : post
   summary         : cancle
   description    : 取消 PullRequest
   path            : user,project,iid

  ###

  cancle: (user,project,iid) =>
    @debug "PullRequests::cancle()"

    @coding.pullRequest.cancle user,project,iid,(data) =>
      @showData data

  ###

   method            : get
   summary         : comments
   description    : PullRequest 评论列表
   path            : user,project,iid

  ###

  comments: (user,project,iid) =>
    @debug "PullRequests::comments()"

    @coding.pullRequest.comments user,project,iid,(data) =>
      @showData data

  ###

   method            : get
   summary         : commits
   description    : 获取某个 PullRequest 的评论
   path            : user,project,iid

  ###

  commits: (user,project,iid) =>
    @debug "PullRequests::commits()"

    @coding.pullRequest.commits user,project,iid,(data) =>
      @showData data

  ###

   method            : post
   summary         : merge
   description    : 合并 PullRequest
   path            : user,project,iid
   query            : message

  ###

  merge: (user,project,iid) =>
    @debug "PullRequests::merge()"

    @prompt.get [{"name":"message","description":"Enter message","type":"string","required":false}],(err,params)=>
      if err
        return err
      params = @parseParames params,[],["message"],[],[]
      @coding.pullRequest.merge user,project,iid,params,(data) =>
        @showData data

  ###

   method            : post
   summary         : refuse
   description    : 拒绝 PullRequest
   path            : user,project,iid

  ###

  refuse: (user,project,iid) =>
    @debug "PullRequests::refuse()"

    @coding.pullRequest.refuse user,project,iid,(data) =>
      @showData data

  ###

   method            : get
   summary         : list
   description    : PullRequest 列表
   path            : user,project,status
   query            : page,pageSize

  ###

  list: (user,project,status) =>
    @debug "PullRequests::list()"

    @prompt.get [{"name":"page","description":"Enter page","type":"integer","required":false},{"name":"pageSize","description":"Enter pageSize","type":"integer","required":false}],(err,params)=>
      if err
        return err
      params = @parseParames params,[],["page","pageSize"],[],[]
      @coding.pullRequest.list user,project,status,params,(data) =>
        @showData data


module.exports = (cmd) -> new PullRequests cmd